apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: stage
  template:
    metadata:
      name: 'monitoring-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Kritik72/k8s-helm-config.git
        targetRevision: master
        path: apps/monitoring/chart
        helm:
          valueFiles:
            - ../envs/{{env}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'monitoring-{{env}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
